### ISSUE TITLE
publish on https://crates.io/search?q=telefork?

### ISSUE THREAD

**Issue by evandrix** [trishume/telefork#1]
so that `cargo install telefork` just works

**Comment by trishume** [comment]
Currently telefork is just a tech demo, if you want to actually use it for something you probably want to modify it first. I'm reluctant to do anything that makes it seem like something you might actually want to use. Maybe if someone contributes fixes for some of the TODO areas, or at least makes it fail gracefully when you try to use things that don't work like file descriptors.

**Comment by evandrix** [comment]
aww :/
